parameters:
    secret: 82980092f69f40f2f3cc63d143f38fff93f2c1ff
    locale_fallback: en
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true