ezpublish:
    system:
        eng:
            content_view:
            location_view:
                full:
                    home:
                        template: KaliopEzobjectWorkshopBundle:Home:full.html.twig
                        controller: KaliopEzobjectWorkshopBundle:Home:index
                        match:
                            Identifier\ContentType: "landing_page"
                    folder:
                        template: KaliopEzobjectWorkshopBundle:Folder:full.html.twig
                        controller: KaliopEzobjectWorkshopBundle:Folder:index
                        match:
                            Identifier\ContentType: "folder"
                    article:
                        template: KaliopEzobjectWorkshopBundle:Article:full.html.twig
                        controller: KaliopEzobjectWorkshopBundle:Article:index
                        match:
                            Identifier\ContentType: "article"
                    place_list:
                        template: KaliopEzobjectWorkshopBundle:Place_list:full.html.twig
                        controller: KaliopEzobjectWorkshopBundle:Place:full
                        match:
                            Identifier\ContentType: "place_list"

                line:
                    place_list:
                        template: KaliopEzobjectWorkshopBundle:Place:line.html.twig
                        match:
                            Identifier\ContentType: "place"